import { CompositeHeader, IOType } from "./Table/CompositeHeader.js";
import { OntologyAnnotation } from "./OntologyAnnotation.js";
import { ofArray } from "../fable_modules/fable-library-js.4.22.0/List.js";
import { iterateIndexed, map } from "../fable_modules/fable-library-js.4.22.0/Seq.js";
import { CompositeCell } from "./Table/CompositeCell.js";
import { boxHashSeq, hash } from "./Helper/HashCodes.js";
import { class_type } from "../fable_modules/fable-library-js.4.22.0/Reflection.js";
import { DataContext__Copy, DataContext__set_Description_6DFDD678, DataContext__get_Description, DataContext__set_ObjectType_279AAFF2, DataContext__get_ObjectType, DataContext__set_Unit_279AAFF2, DataContext__get_Unit, DataContext__set_Explication_279AAFF2, DataContext__get_Explication } from "./DataContext.js";

export const DataMapAux_dataHeader = new CompositeHeader(11, [new IOType(2, [])]);

export const DataMapAux_explication = new OntologyAnnotation("Clarification", "NCIT", "http://purl.obolibrary.org/obo/NCIT_C94778");

export const DataMapAux_explicationHeader = new CompositeHeader(3, [DataMapAux_explication]);

export const DataMapAux_unit = new OntologyAnnotation("Unit", "UO", "http://purl.obolibrary.org/obo/UO_0000000");

export const DataMapAux_unitHeader = new CompositeHeader(3, [DataMapAux_unit]);

export const DataMapAux_objectType = new OntologyAnnotation("Data Type", "NCIT", "http://purl.obolibrary.org/obo/NCIT_C42645");

export const DataMapAux_objectTypeHeader = new CompositeHeader(3, [DataMapAux_objectType]);

export const DataMapAux_labelHeader = new CompositeHeader(13, ["Label"]);

export const DataMapAux_descriptionHeader = new CompositeHeader(13, ["Description"]);

export const DataMapAux_generatedByHeader = new CompositeHeader(13, ["Generated By"]);

export const DataMapAux_allowedHeaders = ofArray([DataMapAux_dataHeader, DataMapAux_explicationHeader, DataMapAux_unitHeader, DataMapAux_objectTypeHeader, DataMapAux_descriptionHeader, DataMapAux_generatedByHeader]);

export function DataMapAux_getOntologyColumn(f, dataContexts) {
    const collection = map((dc) => {
        const matchValue = f(dc);
        if (matchValue == null) {
            return CompositeCell.emptyTerm;
        }
        else {
            return new CompositeCell(0, [matchValue]);
        }
    }, dataContexts);
    return Array.from(collection);
}

export function DataMapAux_getStringColumn(f, dataContexts) {
    const collection = map((dc) => {
        const matchValue = f(dc);
        if (matchValue == null) {
            return CompositeCell.emptyFreeText;
        }
        else {
            return new CompositeCell(1, [matchValue]);
        }
    }, dataContexts);
    return Array.from(collection);
}

export function DataMapAux_setOntologyColumn(f, column, dataContexts) {
    iterateIndexed((i, cell) => {
        if (cell.tag === 0) {
            f(dataContexts[i], cell.fields[0]);
        }
    }, column);
}

export function DataMapAux_setStringColumn(f, column, dataContexts) {
    iterateIndexed((i, cell) => {
        if (cell.tag === 1) {
            f(dataContexts[i], cell.fields[0]);
        }
    }, column);
}

export function DataMapAux_SanityChecks_rowIndexInBoundaries(row, dataContexts) {
    if (row < 0) {
        throw new Error("Row index must be greater or equal to 0.");
    }
    if (row >= dataContexts.length) {
        throw new Error("Row index must be less than the number of rows.");
    }
}

export function DataMapAux_SanityChecks_lengthOfNewColumn(newColumn, dataContexts) {
    if (newColumn.length !== dataContexts.length) {
        throw new Error("Length of new column does not match length of data contexts.");
    }
}

export class DataMap {
    constructor(dataContexts) {
        this.staticHash = 0;
        this["dataContexts@108"] = dataContexts;
    }
    Equals(obj) {
        const this$ = this;
        return hash(this$) === hash(obj);
    }
    GetHashCode() {
        const this$ = this;
        return boxHashSeq(this$["dataContexts@108"]) | 0;
    }
}

export function DataMap_$reflection() {
    return class_type("ARCtrl.DataMap", undefined, DataMap);
}

export function DataMap_$ctor_4E3220A7(dataContexts) {
    return new DataMap(dataContexts);
}

export function DataMap__get_StaticHash(this$) {
    return this$.staticHash;
}

export function DataMap__set_StaticHash_Z524259A4(this$, value) {
    this$.staticHash = (value | 0);
}

export function DataMap__get_DataContexts(this$) {
    return this$["dataContexts@108"];
}

export function DataMap_init() {
    return DataMap_$ctor_4E3220A7([]);
}

export function DataMap__GetExplicationColumn(this$) {
    return DataMapAux_getOntologyColumn(DataContext__get_Explication, this$["dataContexts@108"]);
}

export function DataMap__SetExplicationColumn_C98E589(this$, cells) {
    DataMapAux_setOntologyColumn((dc, oa) => {
        DataContext__set_Explication_279AAFF2(dc, oa);
    }, cells, this$["dataContexts@108"]);
}

export function DataMap__GetUnitColumn(this$) {
    return DataMapAux_getOntologyColumn(DataContext__get_Unit, this$["dataContexts@108"]);
}

export function DataMap__SetUnitColumn_C98E589(this$, cells) {
    DataMapAux_setOntologyColumn((dc, oa) => {
        DataContext__set_Unit_279AAFF2(dc, oa);
    }, cells, this$["dataContexts@108"]);
}

export function DataMap__GetObjectTypeColumn(this$) {
    return DataMapAux_getOntologyColumn(DataContext__get_ObjectType, this$["dataContexts@108"]);
}

export function DataMap__SetDataTypeColumn_C98E589(this$, cells) {
    DataMapAux_setOntologyColumn((dc, oa) => {
        DataContext__set_ObjectType_279AAFF2(dc, oa);
    }, cells, this$["dataContexts@108"]);
}

export function DataMap__GetLabelColumn(this$) {
    return DataMapAux_getStringColumn((dc) => dc.Name, this$["dataContexts@108"]);
}

export function DataMap__SetLabelColumn_C98E589(this$, cells) {
    DataMapAux_setStringColumn((dc, s) => {
        dc.Name = s;
    }, cells, this$["dataContexts@108"]);
}

export function DataMap__GetDescriptionColumn(this$) {
    return DataMapAux_getStringColumn(DataContext__get_Description, this$["dataContexts@108"]);
}

export function DataMap__SetDescriptionColumn_C98E589(this$, cells) {
    DataMapAux_setStringColumn((dc, s) => {
        DataContext__set_Description_6DFDD678(dc, s);
    }, cells, this$["dataContexts@108"]);
}

export function DataMap__GetDataContext_Z58338566(this$, row, SkipValidation) {
    DataMapAux_SanityChecks_rowIndexInBoundaries(row, this$["dataContexts@108"]);
    return this$["dataContexts@108"][row];
}

export function DataMap_getDataContext_Z58338566(row, SkipValidation) {
    return (dm) => DataMap__GetDataContext_Z58338566(dm, row, SkipValidation);
}

export function DataMap__Copy(this$) {
    let collection;
    return DataMap_$ctor_4E3220A7((collection = map(DataContext__Copy, this$["dataContexts@108"]), Array.from(collection)));
}

